### ISSUE TITLE
cc icons are wrong colour and there's no bottom padding 

### ISSUE THREAD

**Issue by simonfossom** [themoonsheep/moonsheep.org#11]
Icons should be same colour as links.

![image](https://user-images.githubusercontent.com/8134850/36785838-983f85d6-1c84-11e8-962c-bf5e804cd35b.png)
and it should be like this:
![image](https://user-images.githubusercontent.com/8134850/36785850-a588a18c-1c84-11e8-9f1a-826d25ef0762.png)
Between links and icons, there should be 60px padding and another 60px to the bottom of the page.

**Comment by KrzysztofMadejski** [comment]
Ping @IronRunes I still see that.

**Comment by IronRunes** [comment]
done now
