### ISSUE TITLE
Misalignment: general use cases

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/moonsheep.org#2]
It would be nice if the text and icons were aligned horizontally.

![misalign1](https://user-images.githubusercontent.com/849975/36379786-d02c16b2-1577-11e8-91a3-5f2970083ab6.png)

**Comment by simonfossom** [comment]
Adjusted it in design!

**Comment by IronRunes** [comment]
fixed in [https://github.com/themoonsheep/moonsheep.org/commit/ac836c94d0c6e2ce3015d91d9204dab04b697212](url)

**Comment by simonfossom** [comment]
It's not by design. We talked that you'll put this in the html table... 
![image](https://user-images.githubusercontent.com/8134850/36782270-b6504684-1c78-11e8-8af7-98aa87eb8784.png)

**Comment by IronRunes** [comment]
I thought we were putting the pros and cons in an html table (done that, btw). I aligned icons & related text horizontally, as per Krzystof's request.
No biggie though, can do

**Comment by KrzysztofMadejski** [comment]
On my chrome (Version 64.0.3282.186, Ubuntu 17.04) the text is aligned, but icons still are not aligned horizontally (see below).

Let me know @IronRunes if I should test some css live.

![screenshot from 2018-02-28 09-01-45](https://user-images.githubusercontent.com/849975/36791532-22e50e78-1c66-11e8-9aae-944ab4c278ca.png)

**Comment by IronRunes** [comment]
so you want everything aligned horizontally, and not reciprocally (i.e. icon aligned to text, as is now). 
ok, will do.

**Comment by IronRunes** [comment]
Done
