### ISSUE TITLE
Misalignment: Pros & Cons

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/moonsheep.org#3]
The pros & cons in rows are relating to each other so it would be good to have them aligned.

![misalign2](https://user-images.githubusercontent.com/849975/36379946-6a449b02-1578-11e8-8681-3065c8903293.png)

**Comment by simonfossom** [comment]
Totally right
![image](https://user-images.githubusercontent.com/8134850/36382261-9ac0f9f0-1588-11e8-8197-b99f6eb92b6b.png)

That's how it should be. I'll sync inVision preview

**Comment by IronRunes** [comment]
Done
