### ISSUE TITLE
General links:

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/moonsheep.org#6]
### Top menu
Documentation: https://docs.google.com/document/d/1HdxOXWgfzClokilRHaRrX897iHI4hTOf5tZd4t930cs/edit?usp=sharing
Github: https://github.com/themoonsheep

### Body
Assess your needs: https://docs.google.com/document/d/1IidmIa-pJcPvIi_OTELtehLVjPZzD5_XiSOUGsWFMFs/edit

### Footer
Github: https://github.com/themoonsheep
Contact us: mailto:contact@moonsheep.org
Join the Slack: https://slack.transparencee.org/
CC license: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by simonfossom** [comment]
@KrzysztofMadejski 
You need to add links to Opora and K-Monitor deployments in sandbox mode for Demos

**Comment by simonfossom** [comment]
- [x] Preconditions ➞ to homepage section “Don’t know if it’s right for you?”
- [x] “Read more” on each case study ➞ to each project's webpage

**Comment by KrzysztofMadejski** [comment]
- [x] Demo -> For now let it link to "Case studies" section on the homepage
- I'll add links to platforms later

**Comment by KrzysztofMadejski** [comment]
@IronRunes I've set the links. Just one issue I don't know how to solve
- [ ] the http://moonsheep.org/#preconditions scrolls too low and the section header is not visible.
