### ISSUE TITLE
Cycle through Case Studies

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/moonsheep.org#7]
Move arrows a bit up (in relation to the original mockup)

![image](https://user-images.githubusercontent.com/849975/36380808-8447d160-157b-11e8-9fc3-ea790a22e29e.png)

Cycle between K-Monitor and #4

**Comment by IronRunes** [comment]
pretty much done, I think

**Comment by KrzysztofMadejski** [comment]
The text below Case Studies ("MPs in Hungary are hiding their assets in scanned PDFs preventing the data from being analysed. By using Moonsheep, K-Monitor showed that data liberation is not rocket science. With a few dozens volunteers we liberated the data just hours after the publication and published it in an open, searchable and comparable database." ) should cycle as well

**Comment by KrzysztofMadejski** [comment]
Also the background filter to lighten it up should be ending right before Case Stories. Now it stretches way down to the bottom (there is also shadow at the bottom of it which I don't see in mockups)

**Comment by IronRunes** [comment]
done now. shadow is there in mockups (see img) 
![screenshot_6](https://user-images.githubusercontent.com/8185000/36786771-e6ace9a4-1c87-11e8-9ddb-9042300c3f41.png)
can remove if you don't like it!

**Comment by KrzysztofMadejski** [comment]
I've meant stretching shadow to the bottom, but I've seen you've fixed that. Thanks!
